# keep this list in run order

import process_s2_swath.common
import process_s2_swath.PrepareWorkingFolder
import process_s2_swath.UnzipRaw
import process_s2_swath.ReadManifests
import process_s2_swath.BuildFileList
import process_s2_swath.RunArcsi
import process_s2_swath.CheckFileExists
import process_s2_swath.GdalTranslate
import process_s2_swath.ConvertToTif
import process_s2_swath.BuildPyramid
import process_s2_swath.BuildPyramids
import process_s2_swath.CheckOutputFilesExist
import process_s2_swath.GenerateMetadata
import process_s2_swath.TransferArdToOutput