# keep this list in run order

import process_s2_swath.common
import process_s2_swath.UnzipRaw
import process_s2_swath.GetInputFileInfo
import process_s2_swath.GetInputFileInfos
import process_s2_swath.GetSatelliteAndOrbitNumber
import process_s2_swath.BuildFileList
import process_s2_swath.ProcessRawToArd
import process_s2_swath.CheckFileExists
import process_s2_swath.CheckFileExistsWithPattern
import process_s2_swath.GdalTranslateKeaToTif
import process_s2_swath.ConvertFilesToTif
import process_s2_swath.OptimiseFiles
import process_s2_swath.BuildPyramidsAndCalculateStats
import process_s2_swath.GenerateMetadata
import process_s2_swath.GenerateProductMetadata
import process_s2_swath.GenerateThumbnail
import process_s2_swath.GenerateThumbnails
import process_s2_swath.FinaliseOutputs