FROM continuumio/miniconda3:latest

#setup app folder
WORKDIR /app

# mute debconf warnings
ENV DEBIAN_FRONTEND=noninteractive

#Install packages
RUN apt-get update && apt-get install apt-utils -y 

# add debian packages required by arcsi
RUN apt-get update && \
    apt-get install -y \
        libmpfr4 \
        libgl1-mesa-glx && \
    apt-get clean

# update conda and install arcsi using conda package manager and clean up (rm tar packages to save space)
RUN conda update -n base conda
RUN conda update --yes -c conda-forge conda && \
    conda install --yes -c conda-forge python=3.7 arcsi && \
    conda update -c conda-forge --all && \
    conda clean --yes -t

# Ugly fixes for dependency versions
#RUN cd /opt/conda/lib && \
#ln -s libgeos-3.5.1.so libgeos-3.5.0.so && \
#ln -s libjpeg.so.9 libjpeg.so.8

# set gdal paths
ENV GDAL_DRIVER_PATH /opt/conda/lib/gdalplugins:$GDAL_DRIVER_PATH
ENV GDAL_DATA /opt/conda/share/gdal

# Create processing paths
RUN mkdir -p /data


