FROM continuumio/miniconda3:latest

#setup app folder
WORKDIR /app

# mute debconf warnings
ENV DEBIAN_FRONTEND=noninteractive

#Install packages
RUN apt-get update && apt-get install apt-utils -y 

# add debian packages required by arcsi
RUN apt-get update && \
    apt-get install -y \
        libmpfr4 \
        libgl1-mesa-glx \
        unzip && \
    apt-get clean

# update conda and install arcsi using conda package manager and clean up (rm tar packages to save space)
# RUN conda update -n base conda

# RUN conda update --yes -c conda-forge conda && \
#     conda create --yes -n arcsienv python=3.5

# RUN /bin/bash -c ". activate arcsienv && \
#     conda install --yes -c conda-forge python=3.5 arcsi && \
#     conda update -c conda-forge --all && \
#     conda clean --yes -t"

# TEMPORARY FIX FOR CONDA ARCSI BUILD
RUN conda create --yes -c conda-forge -n arcsienv python=3.5 libgcc-ng=7.2.0 arcsi openblas

# set gdal paths
ENV GDAL_DRIVER_PATH /opt/conda/lib/gdalplugins:$GDAL_DRIVER_PATH
ENV GDAL_DATA /opt/conda/share/gdal

# Create processing paths
RUN mkdir -p /data

COPY app/exec.sh ./
RUN chmod +rx /app/exec.sh

ENTRYPOINT ["/app/exec.sh"]
