BootStrap: docker
From: jncc/arcsi-base

%runscript
    #!/bin/bash
    . /opt/conda/etc/profile.d/conda.sh
    conda activate base
    #$@ Executes any commands passed in on the singularity run command line.
    $@ 
