BootStrap: docker
From: jncc/arcsi-base:latest

%runscript
    #!/bin/bash
    . /opt/conda/etc/profile.d/conda.sh
    conda activate arcsienv
    #$@ Executes any commands passed in on the singularity run command line.
    $@ 
